name: studiosix-pro
services:
- name: web
  source_dir: /
  github:
    repo: Visionatedigital/StudioSix-Pro
    branch: main
    deploy_on_push: true
  run_command: npm run start:production
  build_command: npm ci && (npm run build || echo "Build failed, but continuing...")
  environment_slug: node-js
  instance_count: 1
  instance_size_slug: basic-xxs
  http_port: 8080
  health_check:
    http_path: /health
    initial_delay_seconds: 30
    period_seconds: 10
    timeout_seconds: 5
    success_threshold: 1
    failure_threshold: 3
  envs:
  - key: NODE_ENV
    value: production
  - key: PORT
    value: "8080"
  - key: GENERATE_SOURCEMAP
    value: "false"
